# Generated by Django 5.2.4 on 2026-04-23 21:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_tenants', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('etage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('type_chambre', models.CharField(choices=[('privee', 'Privée'), ('semi_privee', 'Semi-privée'), ('collective', 'Collective')], max_length=20)),
                ('capacite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('statut', models.CharField(default='libre', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Lit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lit', models.CharField(max_length=5)),
                ('statut', models.CharField(default='libre', max_length=20)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lits', to='hospitalisation.chambre')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_admission', models.DateTimeField(auto_now_add=True)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('hospitalise', 'Hospitalisé'), ('sorti', 'Sorti'), ('transfere', 'Transféré')], default='hospitalise', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('lit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalisation.lit')),
            ],
        ),
        migrations.AddIndex(
            model_name='chambre',
            index=models.Index(fields=['tenant', 'statut'], name='hospitalisa_tenant__69fa0c_idx'),
        ),
        migrations.AddIndex(
            model_name='lit',
            index=models.Index(fields=['statut'], name='hospitalisa_statut_d9f53c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lit',
            unique_together={('chambre', 'numero_lit')},
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['date_admission', 'statut'], name='hospitalisa_date_ad_d69cb5_idx'),
        ),
    ]
