# Generated by Django 5.2.4 on 2026-04-23 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_tenants', '0001_initial'),
        ('rendez_vous', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SalleMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('capacite', models.IntegerField()),
                ('equipements', models.TextField(blank=True)),
                ('statut', models.CharField(default='disponible', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant')),
                ('type_salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salles_medicales.typesalle')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('motif', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='confirmee', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('rendez_vous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rendez_vous.rendezvous')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salles_medicales.sallemedicale')),
            ],
            options={
                'indexes': [models.Index(fields=['salle', 'date_debut'], name='salles_medi_salle_i_4fbb92_idx')],
                'unique_together': {('salle', 'date_debut')},
            },
        ),
        migrations.AddIndex(
            model_name='sallemedicale',
            index=models.Index(fields=['tenant', 'statut'], name='salles_medi_tenant__3c6a8d_idx'),
        ),
    ]
