# Generated by Django 5.2.4 on 2026-04-27 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_alter_utilisateur_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
