# Generated by Django 5.2.4 on 2026-04-27 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_alter_emailverificationtoken_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 28, 22, 20, 35, 560684, tzinfo=datetime.timezone.utc)),
        ),
    ]
