# Generated by Django 5.2.4 on 2026-04-27 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0006_alter_emailverificationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 28, 22, 45, 37, 822129, tzinfo=datetime.timezone.utc)),
        ),
    ]
