# Generated by Django 5.2.4 on 2026-04-28 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0008_alter_emailverificationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 29, 16, 6, 43, 296197, tzinfo=datetime.timezone.utc)),
        ),
    ]
