# Generated by Django 5.2.4 on 2026-05-16 22:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('comptes', '0009_alter_emailverificationtoken_expires_at'),
        ('gestion_tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CINUBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ninu_hash', models.CharField(max_length=64, unique=True)),
                ('date_utilisation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cinu_blacklist',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('CINU', "Carte d'Identité Nationale"), ('DIPLOME', 'Diplôme'), ('CARTE_PRO', 'Carte Professionnelle')], max_length=20)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('ANALYZING', 'En analyse')], default='PENDING', max_length=20)),
                ('nom_fichier_original', models.CharField(max_length=255)),
                ('taille_fichier', models.IntegerField()),
                ('type_mime', models.CharField(default='application/pdf', max_length=100)),
                ('hash_document', models.CharField(blank=True, max_length=64, null=True)),
                ('score_confiance', models.IntegerField(default=0)),
                ('analyse_resultats', models.JSONField(default=dict)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_admin', models.TextField(blank=True)),
                ('motif_rejet', models.CharField(blank=True, max_length=500)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='DocumentBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_document', models.CharField(max_length=64, unique=True)),
                ('type_document', models.CharField(max_length=50)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document_blacklist',
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(default=dict)),
                ('texte_extrait', models.TextField(blank=True)),
                ('informations_extraites', models.JSONField(default=dict)),
                ('qualite_image', models.JSONField(default=dict)),
                ('detection_falsification', models.JSONField(default=dict)),
                ('decision', models.CharField(default='PENDING', max_length=20)),
                ('commentaire_admin', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('date_verification', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'verification_log',
                'ordering': ['-date_verification'],
            },
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='est_verifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='ninu',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='ninu_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='qr_code_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='statut_carte_pro',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='statut_cinu',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='statut_diplome',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='version_cinu',
            field=models.CharField(default='V1', max_length=5),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 17, 22, 6, 17, 400934, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['ninu_hash'], name='utilisateur_ninu_ha_0a5e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['statut_cinu'], name='utilisateur_statut__79abe2_idx'),
        ),
        migrations.AddField(
            model_name='cinublacklist',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='valide_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentblacklist',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificationlog',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificationlog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.document'),
        ),
        migrations.AddField(
            model_name='verificationlog',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cinublacklist',
            index=models.Index(fields=['ninu_hash'], name='cinu_blackl_ninu_ha_7030b4_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['utilisateur', 'type_document'], name='document_utilisa_bab5d9_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['statut'], name='document_statut_3f51a5_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['hash_document'], name='document_hash_do_98575b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentblacklist',
            index=models.Index(fields=['hash_document'], name='document_bl_hash_do_407caa_idx'),
        ),
    ]
