# Generated by Django 5.2.4 on 2026-06-17 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0010_cinublacklist_document_documentblacklist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinublacklist',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='document',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='document',
            name='valide_par',
        ),
        migrations.RemoveField(
            model_name='verificationlog',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentblacklist',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='verificationlog',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='verificationlog',
            name='utilisateur',
        ),
        migrations.RemoveIndex(
            model_name='utilisateur',
            name='utilisateur_ninu_ha_0a5e2a_idx',
        ),
        migrations.RemoveIndex(
            model_name='utilisateur',
            name='utilisateur_statut__79abe2_idx',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_validation',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='est_verifie',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='ninu',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='ninu_hash',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='qr_code_data',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='statut_carte_pro',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='statut_cinu',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='statut_diplome',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='valide_par',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='version_cinu',
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 18, 18, 9, 10, 489271, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='CINUBlacklist',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentBlacklist',
        ),
        migrations.DeleteModel(
            name='VerificationLog',
        ),
    ]
