# Generated by Django 5.2.4 on 2026-06-17 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0011_remove_cinublacklist_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 18, 18, 10, 27, 33000, tzinfo=datetime.timezone.utc)),
        ),
    ]
