# Generated by Django 5.2.4 on 2026-06-17 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0013_alter_emailverificationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 18, 18, 18, 24, 224055, tzinfo=datetime.timezone.utc)),
        ),
    ]
