# Generated by Django 5.2.4 on 2026-08-04 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0014_alter_emailverificationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 5, 16, 51, 16, 8872, tzinfo=datetime.timezone.utc)),
        ),
    ]
