# Generated by Django 5.2.4 on 2026-08-04 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0015_alter_emailverificationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 5, 17, 3, 25, 197535, tzinfo=datetime.timezone.utc)),
        ),
    ]
